<a href="https://colab.research.google.com/github/Divyanshi082004/ml-project/blob/dev/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy- Numerical Python

Advantages of Numpy Arrays:

1.Allows several mathematical Operations

2.Faster Operations






In [2]:
import numpy as np

List Vs NumPy- Time taken

In [3]:
from time import process_time

Time taken by a list

In [4]:
python_list = [ i for i in range(10000)]
start_time = process_time()
python_list = [i+5 for i in python_list]
end_time = process_time()
print(end_time - start_time)

0.0010739969999999932


In [5]:
np_array = np.array([i for i in range(10000)])
start_time = process_time()
np_array += 5
end_time = process_time()
print(end_time - start_time)

0.00022620400000006313


NumPy Array

In [6]:
# list
list1= [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [7]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [8]:
#creating a 1 dimensional array
a = np.array([1,2,3,4,5,6])
print(a)
a.shape

[1 2 3 4 5 6]


(6,)

In [9]:
#creating 2D array
b = np.array([(1,2,3),(4,5,6)])
print(b)
b.shape

[[1 2 3]
 [4 5 6]]


(2, 3)

In [10]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial Placeholders in numpy arrays

In [11]:
# create a numpy array of Zero
x = np.zeros(( 4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [12]:
#create a numpy array of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [13]:
# create a numpy array of a particular value
z = np.full((5,4),4)
print(z)

[[4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]]


In [14]:
#creating identity matrix
i = np.eye(4)
print(i)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [15]:
#method two to create identity matrix
i = np.identity(3)
print(i)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
b = np.array([[1,2],[3,4]])
print(b)

[[1 2]
 [3 4]]


shape – Data Structure Ki Geometry
Working:

Tuple return karta hai

First value = rows

Second value = columns

Internally array me dimensions metadata store hota hai

In [17]:
print(b.shape)

(2, 2)


In [18]:
x1 = np.array([1,2,3,4,5,6])
print(x1)

[1 2 3 4 5 6]


Reshape
Deep Working:

Data copy nahi karta (agar possible ho)

Sirf dimension metadata change karta hai

Total elements same rehne chahiye

In [19]:
x1 = x1.reshape(2,3)
print(x1)

[[1 2 3]
 [4 5 6]]


Arange: Sequence generator
Working:

Start se stop tak values generate karta hai

Stop include nahi hota

Step size bhi de sakte ho

In [20]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Mathematical operations
NumPy:

Python loop use nahi karta

C-based vectorized operations karta hai

Har index par operation apply hota hai

In [22]:
A = np.array([1,2,3])
B = np.array([4,5,6])
print(A+B)
print(A-B)
print(A*B)
print(A/B)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


Dot product: Ye Linear Regression, Neural Network sab me use hota hai.

Formula: W.X+b

In [23]:
np.dot(A,B)

np.int64(32)

mean()
Working:

Formula: ∑𝑥/𝑛
Internally:

Sum calculate karta hai

Divide by number of elements

Axis parameter:

np.mean(matrix, axis=0)  # column wise
np.mean(matrix, axis=1)  # row wise

ML me:
Feature scaling

In [24]:
np.mean(A)

np.float64(2.0)

std() – Standard Deviation
Formula: ∑(𝑥−𝑚𝑒𝑎𝑛)^2/𝑛
ML me:
Normalization:

𝑋𝑛𝑒𝑤=𝑋−mean/std



In [25]:
np.std(B)

np.float64(0.816496580927726)

Indexing & Slicing
Working:

: means all rows

1 means second column

Internally memory offset calculate hota hai

In [26]:
data = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

print(data[0])        # first row
print(data[:,1])      # second column
print(data[0:2,1:3])  # slicing

[1 2 3]
[2 5 8]
[[2 3]
 [5 6]]


np.random.rand()
Working:

Uniform distribution (0 to 1)

Pseudo-random generator use karta hai

Seed set kar sakte ho reproducibility ke liye

In [27]:
np.random.rand(2,2)
np.random.randint(1,10, size=(3,3))

array([[4, 3, 3],
       [8, 3, 1],
       [8, 5, 2]])

In [28]:
a = np.array([1,2,3])
b = 2
print(a * b)

[2 4 6]


np.matmul() or A @ B

working: matrix multiplication rule follow krta hai:
(m*n)@(n*p)
Result: (m*p)

In [29]:
A = np.array([[1,2],
              [3,4]])

B = np.array([[5,6],
              [7,8]])

np.matmul(A,B)

array([[19, 22],
       [43, 50]])

In [30]:
A @ B

array([[19, 22],
       [43, 50]])